server:
  port: 8401
spring:
  application:
    name: cloud-ali-sentinel-service
  cloud:
    nacos:
      discovery:
        # NACOS服务注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        # 配置 Sentinel dashboard地址
        dashboard: localhost:8080
        # 默认8719端口，假如被占用会自动从8719开始依次+1扫描，直到找到未被占用的端口
        port: 8719
        # sentinel持久化配置
        datasourece:
          ds1:
            nacos:
              server-addr: localhost:8848
              dataId: cloudalibaba-sentinel-service
              groupId: DEFAULT_GROUP
              data-type: json
              rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 激活Sentinel 对 openfeign 的支持
feign:
  sentinel:
    enabled: true


